### ISSUE TITLE
Feature request: Ability to toggle line breaks

### ISSUE THREAD

**Issue by angeloashmore** [asyarb/markdown-react-renderer#2]
Adding the ability to toggle line breaks would be useful.

The package currently applies `remark-breaks` automatically here:

https://github.com/asyarb/markdown-react-renderer/blob/2fd69547ac51732e4b7a72e9c6563fe7e80c1786/src/index.js#L26

This converts line breaks into `<br />`. There may be times where this is unwanted, such as wrapping long strings to 80ch each.

Something like a `breaks` prop could work here, set to `true` by default. The above line would be called conditionally based on the `breaks` prop.

```jsx
<MarkdownRenderer
  markdown={markdown}
  breaks={false}
/>
```

**Comment by asyarb** [comment]
Merged in #3.
